spring:
  application:
    name: AuthService
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:postgres@localhost:5432/auth_service
    password: postgres
    username: postgres

  webflux:
    base-path: /auth-service
  rabbitmq:
    host: 192.168.0.75
    port: 5672
    username: thiago
    password: 438537

api:
  security:
    token:
      secret: mySecret

