name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker stop auth-service || true
            docker rm auth-service || true
            docker run -d --name auth-service -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
